# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Input(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, house_id: int=None, age: int=None):  # noqa: E501
        """Input - a model defined in Swagger

        :param house_id: The house_id of this Input.  # noqa: E501
        :type house_id: int
        :param age: The age of this Input.  # noqa: E501
        :type age: int
        """
        self.swagger_types = {
            'house_id': int,
            'age': int
        }

        self.attribute_map = {
            'house_id': 'house_id',
            'age': 'age'
        }

        self._house_id = house_id
        self._age = age

    @classmethod
    def from_dict(cls, dikt) -> 'Input':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The input of this Input.  # noqa: E501
        :rtype: Input
        """
        return util.deserialize_model(dikt, cls)

    @property
    def house_id(self) -> int:
        """Gets the house_id of this Input.


        :return: The house_id of this Input.
        :rtype: int
        """
        return self._house_id

    @house_id.setter
    def house_id(self, house_id: int):
        """Sets the house_id of this Input.


        :param house_id: The house_id of this Input.
        :type house_id: int
        """

        self._house_id = house_id

    @property
    def age(self) -> int:
        """Gets the age of this Input.


        :return: The age of this Input.
        :rtype: int
        """
        return self._age

    @age.setter
    def age(self, age: int):
        """Sets the age of this Input.


        :param age: The age of this Input.
        :type age: int
        """

        self._age = age
